In [2]:
import numpy as np

[Reference](numpy.pdf)

In [5]:
a = np.array([1, 4, 5, 8], float)
a[1:3]

array([ 4.,  5.])

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [10]:
a[1,2]

6.0

In [11]:
a[1,:]

array([ 4.,  5.,  6.])

In [13]:
a.shape

(2, 3)

In [15]:
a.dtype

dtype('float64')

In [16]:
len(a)

2

In [17]:
2 in a

True

In [21]:
a = np.array(range(10), float)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

The **reshape** function creates a new array and does not modify the original.

In [22]:
a = a.reshape((5, 2))
a

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

The **copy** method is used to create an actual copy.

In [24]:
c = a.copy()

In [25]:
c

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.]])

Lists can be created from arrays

In [26]:
a.tolist()

[[0.0, 1.0], [2.0, 3.0], [4.0, 5.0], [6.0, 7.0], [8.0, 9.0]]

In [27]:
list(a)

[array([ 0.,  1.]),
 array([ 2.,  3.]),
 array([ 4.,  5.]),
 array([ 6.,  7.]),
 array([ 8.,  9.])]

In [29]:
b = np.array([1, 2, 3], float)

In [30]:
list(b)

[1.0, 2.0, 3.0]

In [31]:
b.tolist()

[1.0, 2.0, 3.0]

Fill an array with a value

In [35]:
a = np.array([1, 2, 3], float)
a.fill(4)
a

array([ 4.,  4.,  4.])

Transpose an array

In [37]:
a = np.array(range(6), float).reshape((2, 3))
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.]])

In [39]:
a = a.transpose()
a

array([[ 0.,  3.],
       [ 1.,  4.],
       [ 2.,  5.]])